/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117068-g0c9fe2b232-20240918"
#endif /* AVUTIL_FFVERSION_H */
